rm build essential

diff --git a/solv-debian/debian/postinst b/solv-debian/debian/postinst
--- a/solv-debian/debian/postinst
+++ b/solv-debian/debian/postinst
@@ -3,6 +3,12 @@
 
 set -e
 
+handle_error() {
+    echo "Error occurred: $1"
+    exit 1
+}
+
+
 case "$1" in
     configure)
     ;;
@@ -15,10 +21,6 @@ case "$1" in
         exit 1
     ;;
 esac
-
-## Install build-essential
-sudo apt update
-sudo apt install -y build-essential
 
 # Check if nodenv is already installed for solv user
 if [ ! -d "/home/solv/.nodenv" ]; then
@@ -37,9 +39,9 @@ if [ ! -d "/home/solv/.nodenv" ]; then
     sudo -u solv git clone https://github.com/nodenv/node-build.git /home/solv/.nodenv/plugins/node-build
     sudo -u solv git clone https://github.com/nodenv/nodenv-aliases.git /home/solv/.nodenv/plugins/nodenv-aliases;
     chown solv:solv /home/solv/.nodenv/bin/nodenv;
-    sudo -u solv nodenv install 18.17.1;
-    sudo -u solv nodenv global 18.17.1;
-    echo "eval \"\$(nodenv init - zsh)\"" >> /home/solv/.zshrc;
+    sudo -u solv nodenv install 18.17.1 || handle_error "Failed to install node version 18.17.1";
+    sudo -u solv nodenv global 18.17.1 || handle_error "Failed to set global node version to 18.17.1";
+    echo "eval \"\$(nodenv init - zsh)\"" >> /home/solv/.zshrc || handle_error "Failed to add nodenv init to zshrc";
 fi
 
 if [ ! -d "/mt/solana" ]; then
